apiVersion: v1
kind: Service
metadata:
  name: cd-example-url
spec:
  type: NodePort
  ports:
    - name: app-port
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
     name: cd-example